---
title: "Chapter 03"
description: |
  Comparing Sequences
output:
  distill::distill_article:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```


| TOC                             | Content (click for jumping to examples)  |
|-------------------------------------|-------------------------------|
| 3.1 Dissimilarity measures to compare sequences                  | No code for this section |
| 3.2 Alignment techniques                                         | [Create example sequences](rChapter3-2.html) |
|                                                                  | [Optimal matching (OM)](rChapter3-2.html) |
|                                                                  | [Assigning costs to the alignment operations](rChapter3-2.html) |
| 3.3 Alignment-based extensions of OM                             | [Alternative OM-bases metrics to align sequences](rChapter3-3.html) |
| 3.4 Nonalignment techniques                                      | [Alternative metrics to align sequences](rChapter3-4.html) |
| 3.5 Comparing dissimilarity matrices                             | [Correlation for dissimilarity matrices](rChapter3-5.html) |
| 3.6 Comparing sequences of different length                      | No code for this section |
| 3.7	Beyond the standard full-sample pairwise sequence comparison | [Alternative options to compare sequences](rChapter3-7.html) |


Chapter 3 introduces techniques to compare whole sequences. After having reviewed the available options, we offer a tool to compare across the dissimilarity matrices that result from the use of different dissimilarity measures... [to be finalized]
