---
title: "Chapter 02"
description: |
  Defining, Describing, and Visualizing Sequences
output:
  distill::distill_article:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

| TOC                      | Content (click for jumping to examples)  |
|-------------------------------------|-------------------------------|
| 2.1  Basic Concepts and Terminology | [Sequence data formats](rChapter2-1.html) |
| 2.2  Defining Sequences             | [Sequence length and granularity](rChapter2-2.html)     |
| 2.3	Description of Sequence Data I  | [Basic Description](rChapter2-3.html) |
| 2.4 Visualization of Sequence Data  | [Color palette: Grayscale Edition](rChapter2-4_grayscale.html)      |
|                                     | [Color palette: Colored Edition](rChapter2-4_color.html)  |
|                                     | [2.4.1 Data summarization graphs](rChapter2-4-1.html)  |
|                                     | [2.4.2 Data representation graphs](rChapter2-4-2.html)  |
|                                     | [ggplotify sequence data plots (bonus material)](rChapter2-4_ggseqplot.html)  |
| 2.5 Description of Sequence Data II | [Unidimensional and composite indices](rChapter2-5.html)    | 


Chapter 2 introduces the basic concepts and discusses how to define sequence data. The corresponding material provided on this site shows [`{TraMineR}`](http://traminer.unige.ch){target="_blank"}'s capabilities of processing different data formats. We further illustrate 
how the alphabet and the granularity of sequences can be easily changed with [`{TraMineR}`](http://traminer.unige.ch){target="_blank"}'s built-in helper functions.

With visualization being one of the key features of sequence analysis, we provide extensive material on optimizing the quality of figures by choosing appropriate color palettes. Although we highly recommend using colors for visualizing sequences, the associated print-costs are often prohibitively high (for instance, in the case of our book). We therefore provide some material illustrating how to produce acceptable results by using a grayscale color palette and by adding texture.

We further show useful commands for a comprehensive description of the sequence data. Finally, we turn to more advanced composite measures of sequence complexity. These indices are not only interesting in themselves, but also because they can be used either as independent or as dependent variable in subsequent regression analyses. 
